export const LOAD_RESOURCES_ERROR = 'LOAD_RESOURCES_ERROR'
export const LOAD_ERROR_HAPPENED = 'LOAD_ERROR_HAPPENED'
export const LOAD_APP_INIT_FAILED = 'LOAD_APP_INIT_FAILED'
export const LOAD_DUPLICATE_WITHOUT_PATH = 'LOAD_DUPLICATE_WITHOUT_PATH'
